### ISSUE TITLE
关于空调控制器和电暖、水暖温控器

### ISSUE THREAD

**Issue by GitHubMrWhy** [hdcola/hdhome#1]
很受启发，有2个问题想请教 @hdcola 

1.中弘的控制器是每个内机一个？那么所有控制器都得和网管做网线的直连？
2.电暖、水暖温控器如果原来有有线控制器都可以直接改？如果原来没有接线的话有什么办法？

**Comment by czn73126** [comment]
只要接在任一一个室内机上就可以了，优酷上有视频。不过还是对接线感到很困惑，不知道@hdcola能否详细介绍一下呢？

**Comment by hdcola** [comment]
> 很受启发，有2个问题想请教 @hdcola
> 
> 1.中弘的控制器是每个内机一个？那么所有控制器都得和网管做网线的直连？
中弘的控制器是每个外机一个，只是接内机就好，需要看你的品牌。


> 2.电暖、水暖温控器如果原来有有线控制器都可以直接改？如果原来没有接线的话有什么办法？
电暖温控器可以直接改的，水暖的要再看一下，我没用过 :(

**Comment by hdcola** [comment]
> 只要接在任一一个室内机上就可以了，优酷上有视频。不过还是对接线感到很困惑，不知道@hdcola能否详细介绍一下呢？

我更新了文档，附上了照片，你是什么空调？
